{% set name = "osrf_pycommon" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/osrf/osrf_pycommon/archive/refs/tags/{{ version }}.tar.gz
  sha256: b369b0d4d81bf3e9f89b38d5b81a957c7e435715e8e9ff06104b975b6e90b119

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - osrf_pycommon

about:
  home: https://github.com/osrf/osrf_pycommon
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Commonly needed Python modules used by Python software developed at OSRF'
  dev_url: https://github.com/osrf/osrf_pycommon

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
